[package]
name = "simplerays-test"
version = "0.1.0"
authors = ["dranikpg"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "*"
num_cpus = "0.2"
scoped_threadpool = "0.1.9"
stackvec="*"
obj-rs = "0.6"
